// <auto-generated />
using System;
using System.Collections.Generic;
using EfCoreMapping.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfCoreMapping.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(PostgresAppDbContext))]
    [Migration("20260617170052_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EfCoreMapping.Domain.Transfer", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Key"));

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "EfCoreMapping.Domain.Transfer.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("Amount");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "EfCoreMapping.Domain.Transfer.Amount#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("varchar(3)")
                                        .HasColumnName("CurrencyCode");

                                    b2.Property<int>("DecimalPlaces")
                                        .HasColumnType("integer")
                                        .HasColumnName("CurrencyDecimalPlaces");
                                });
                        });

                    b.HasKey("Key");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
